# Generated by Django 2.1.2 on 2018-10-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Contraseña',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Telefono',
            new_name='tlefono',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
