# Generated by Django 2.1.2 on 2018-10-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20181019_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='clave',
        ),
    ]
