# Generated by Django 2.1.2 on 2018-10-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20181019_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('empresa', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
