# Generated by Django 2.1.2 on 2018-11-02 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20181023_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.CharField(default='a', max_length=35),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='a', max_length=35),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaNac',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
