# Generated by Django 2.1.2 on 2018-11-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20181102_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombre1',
        ),
    ]
