# Generated by Django 2.1.2 on 2018-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20181102_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Raza', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Estado', models.IntegerField()),
            ],
        ),
    ]
