# Generated by Django 2.1.2 on 2018-11-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_perro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='Descripcion',
            new_name='Descripcion_perrp',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='Nombre',
            new_name='Nombre_perro',
        ),
    ]
