# Generated by Django 2.1.2 on 2018-11-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20181105_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='Descripcion_perrp',
        ),
        migrations.AddField(
            model_name='perro',
            name='Descripcion_perro',
            field=models.CharField(default='a', max_length=150),
        ),
        migrations.AlterField(
            model_name='perro',
            name='Estado',
            field=models.CharField(max_length=150),
        ),
    ]
