# Generated by Django 2.1.2 on 2018-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20181105_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='Descripcion_perro',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='perro',
            name='Estado',
            field=models.IntegerField(),
        ),
    ]
